-- =============================================================================
-- ENRIQUECIMENTO DOS CATÁLOGOS — Categories + Skills
-- Idempotente: ON CONFLICT DO NOTHING (Slug/Name unique)
-- =============================================================================

BEGIN;

-- ── Categorias novas (8) ───────────────────────────────────────────────────
INSERT INTO "Categories" ("Id", "Name", "Slug", "Description", "CreatedAt") VALUES
(gen_random_uuid(), 'Áudio e Música',            'audio-musica',           'Gravação, mixagem, masterização, produção musical, voice over, jingles e trilha sonora.',                  NOW()),
(gen_random_uuid(), 'Fotografia',                'fotografia',             'Fotografia de produto, eventos, corporativa, casamento, retoque profissional e edição.',                 NOW()),
(gen_random_uuid(), 'Tradução e Idiomas',        'traducao-idiomas',       'Tradução escrita, juramentada, localização de software (l10n) e internacionalização (i18n).',            NOW()),
(gen_random_uuid(), 'Negócios e Vendas',         'negocios-vendas',        'Plano de negócios, pitch deck, modelagem financeira, vendas B2B, captação de investimento.',            NOW()),
(gen_random_uuid(), 'Jurídico',                  'juridico',               'Contratos, LGPD, direito digital, marcas e patentes, termos de uso e política de privacidade.',          NOW()),
(gen_random_uuid(), 'Educação e Tutoria',        'educacao-tutoria',       'Aulas particulares, criação de cursos online, material didático, tutoria especializada e mentoria.',     NOW()),
(gen_random_uuid(), 'Arquitetura e Engenharia',  'arquitetura-engenharia', 'Projetos arquitetônicos, render 3D, AutoCAD, Revit, cálculo estrutural, hidráulica e elétrica.',         NOW()),
(gen_random_uuid(), 'Games e Realidade Virtual', 'games-xr',               'Unity, Unreal Engine, Godot, game design, modelagem 3D para games, realidade virtual e aumentada.',      NOW())
ON CONFLICT ("Slug") DO NOTHING;

-- ── Skills: expansões dos grupos existentes ────────────────────────────────
INSERT INTO "Skills" ("Id", "Name", "Group", "CreatedAt") VALUES
-- Backend
(gen_random_uuid(), 'Symfony',           'Backend', NOW()),
(gen_random_uuid(), 'Ruby on Rails',     'Backend', NOW()),
(gen_random_uuid(), 'Elixir',            'Backend', NOW()),
(gen_random_uuid(), 'Phoenix Framework', 'Backend', NOW()),
(gen_random_uuid(), 'MediatR',           'Backend', NOW()),
(gen_random_uuid(), 'Hangfire',          'Backend', NOW()),
(gen_random_uuid(), 'SignalR',           'Backend', NOW()),
(gen_random_uuid(), 'Apache Kafka',      'Backend', NOW()),
(gen_random_uuid(), 'RabbitMQ',          'Backend', NOW()),
(gen_random_uuid(), 'MassTransit',       'Backend', NOW()),
(gen_random_uuid(), 'AutoMapper',        'Backend', NOW()),
(gen_random_uuid(), 'FluentValidation',  'Backend', NOW()),
(gen_random_uuid(), 'Quartz.NET',        'Backend', NOW()),
(gen_random_uuid(), 'ASP.NET MVC',       'Backend', NOW()),
(gen_random_uuid(), 'WebSockets',        'Backend', NOW()),
(gen_random_uuid(), 'MinIO',             'Backend', NOW()),
-- Frontend
(gen_random_uuid(), 'Astro',         'Frontend', NOW()),
(gen_random_uuid(), 'SolidJS',       'Frontend', NOW()),
(gen_random_uuid(), 'Qwik',          'Frontend', NOW()),
(gen_random_uuid(), 'htmx',          'Frontend', NOW()),
(gen_random_uuid(), 'Three.js',      'Frontend', NOW()),
(gen_random_uuid(), 'D3.js',         'Frontend', NOW()),
(gen_random_uuid(), 'Lit',           'Frontend', NOW()),
(gen_random_uuid(), 'Stimulus',      'Frontend', NOW()),
(gen_random_uuid(), 'Alpine.js',     'Frontend', NOW()),
(gen_random_uuid(), 'PostCSS',       'Frontend', NOW()),
(gen_random_uuid(), 'Chart.js',      'Frontend', NOW()),
(gen_random_uuid(), 'Mantine',       'Frontend', NOW()),
(gen_random_uuid(), 'Radix UI',      'Frontend', NOW()),
(gen_random_uuid(), 'shadcn/ui',     'Frontend', NOW()),
-- Mobile
(gen_random_uuid(), 'ARKit',                  'Mobile', NOW()),
(gen_random_uuid(), 'ARCore',                 'Mobile', NOW()),
(gen_random_uuid(), 'NativeScript',           'Mobile', NOW()),
(gen_random_uuid(), 'Kotlin Multiplatform',   'Mobile', NOW()),
(gen_random_uuid(), 'Capacitor',              'Mobile', NOW()),
(gen_random_uuid(), 'RevenueCat',             'Mobile', NOW()),
-- DevOps & Cloud
(gen_random_uuid(), 'DigitalOcean',  'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'Cloudflare',    'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'Pulumi',        'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'ArgoCD',        'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'Prometheus',    'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'ELK Stack',     'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'Datadog',       'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'Render',        'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'Fly.io',        'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'Kong',          'DevOps & Cloud', NOW()),
(gen_random_uuid(), 'Traefik',       'DevOps & Cloud', NOW()),
-- Dados & IA
(gen_random_uuid(), 'Hugging Face',         'Dados & IA', NOW()),
(gen_random_uuid(), 'LLM Fine-tuning',      'Dados & IA', NOW()),
(gen_random_uuid(), 'RAG (Retrieval)',      'Dados & IA', NOW()),
(gen_random_uuid(), 'Pinecone',             'Dados & IA', NOW()),
(gen_random_uuid(), 'Weaviate',             'Dados & IA', NOW()),
(gen_random_uuid(), 'Apache Spark',         'Dados & IA', NOW()),
(gen_random_uuid(), 'Apache Airflow',       'Dados & IA', NOW()),
(gen_random_uuid(), 'dbt',                  'Dados & IA', NOW()),
(gen_random_uuid(), 'Snowflake',            'Dados & IA', NOW()),
(gen_random_uuid(), 'BigQuery',             'Dados & IA', NOW()),
(gen_random_uuid(), 'Tableau',              'Dados & IA', NOW()),
(gen_random_uuid(), 'Looker',               'Dados & IA', NOW()),
(gen_random_uuid(), 'Anthropic Claude API', 'Dados & IA', NOW()),
-- Design
(gen_random_uuid(), 'Webflow',           'Design', NOW()),
(gen_random_uuid(), 'Framer',            'Design', NOW()),
(gen_random_uuid(), 'Spline',            'Design', NOW()),
(gen_random_uuid(), 'Procreate',         'Design', NOW()),
(gen_random_uuid(), 'Affinity Designer', 'Design', NOW()),
(gen_random_uuid(), 'ProtoPie',          'Design', NOW()),
(gen_random_uuid(), 'Origami Studio',    'Design', NOW()),
(gen_random_uuid(), 'Principle',         'Design', NOW()),
-- Banco de Dados
(gen_random_uuid(), 'ClickHouse',         'Banco de Dados', NOW()),
(gen_random_uuid(), 'Supabase',           'Banco de Dados', NOW()),
(gen_random_uuid(), 'PlanetScale',        'Banco de Dados', NOW()),
(gen_random_uuid(), 'Firebase Firestore', 'Banco de Dados', NOW()),
(gen_random_uuid(), 'InfluxDB',           'Banco de Dados', NOW()),
(gen_random_uuid(), 'TimescaleDB',        'Banco de Dados', NOW()),
(gen_random_uuid(), 'Memcached',          'Banco de Dados', NOW()),
(gen_random_uuid(), 'CockroachDB',        'Banco de Dados', NOW()),
-- Marketing
(gen_random_uuid(), 'Affiliate Marketing',     'Marketing', NOW()),
(gen_random_uuid(), 'ASO (App Store)',         'Marketing', NOW()),
(gen_random_uuid(), 'YouTube Marketing',       'Marketing', NOW()),
(gen_random_uuid(), 'Influencer Marketing',    'Marketing', NOW()),
(gen_random_uuid(), 'X/Twitter Ads',           'Marketing', NOW()),
(gen_random_uuid(), 'Pinterest Marketing',     'Marketing', NOW()),
(gen_random_uuid(), 'RD Station',              'Marketing', NOW()),
(gen_random_uuid(), 'Mailchimp',               'Marketing', NOW()),
(gen_random_uuid(), 'ActiveCampaign',          'Marketing', NOW()),
(gen_random_uuid(), 'Hotmart',                 'Marketing', NOW()),
(gen_random_uuid(), 'Eduzz',                   'Marketing', NOW()),
-- Gestão & Ferramentas
(gen_random_uuid(), 'Asana',         'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'Linear',        'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'Monday.com',    'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'ClickUp',       'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'Pipedrive',     'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'Zoho CRM',      'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'Conta Azul',    'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'Bling',         'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'Omie',          'Gestão & Ferramentas', NOW()),
(gen_random_uuid(), 'RD Station CRM','Gestão & Ferramentas', NOW()),
-- Redação & Conteúdo
(gen_random_uuid(), 'Copywriting de Vendas', 'Redação & Conteúdo', NOW()),
(gen_random_uuid(), 'E-mail Marketing Copy', 'Redação & Conteúdo', NOW()),
(gen_random_uuid(), 'Roteiros para YouTube', 'Redação & Conteúdo', NOW()),
(gen_random_uuid(), 'Newsletter Writing',    'Redação & Conteúdo', NOW()),
(gen_random_uuid(), 'SEO Writing',           'Redação & Conteúdo', NOW()),
(gen_random_uuid(), 'Ghostwriting',          'Redação & Conteúdo', NOW()),
(gen_random_uuid(), 'Press Release',         'Redação & Conteúdo', NOW()),
-- Segurança
(gen_random_uuid(), 'Bug Bounty',         'Segurança', NOW()),
(gen_random_uuid(), 'DevSecOps',          'Segurança', NOW()),
(gen_random_uuid(), 'Threat Modeling',    'Segurança', NOW()),
(gen_random_uuid(), 'ISO 27001',          'Segurança', NOW()),
(gen_random_uuid(), 'IAM',                'Segurança', NOW()),
(gen_random_uuid(), 'Zero Trust',         'Segurança', NOW()),
(gen_random_uuid(), 'SAST',               'Segurança', NOW()),
(gen_random_uuid(), 'DAST',               'Segurança', NOW()),
-- Testes & Qualidade
(gen_random_uuid(), 'Vitest',                'Testes & Qualidade', NOW()),
(gen_random_uuid(), 'Mocha',                 'Testes & Qualidade', NOW()),
(gen_random_uuid(), 'k6',                    'Testes & Qualidade', NOW()),
(gen_random_uuid(), 'JMeter',                'Testes & Qualidade', NOW()),
(gen_random_uuid(), 'Lighthouse',            'Testes & Qualidade', NOW()),
(gen_random_uuid(), 'Cucumber / BDD',        'Testes & Qualidade', NOW()),
(gen_random_uuid(), 'Karate',                'Testes & Qualidade', NOW()),
(gen_random_uuid(), 'Pact',                  'Testes & Qualidade', NOW()),
-- Vídeo & Animação
(gen_random_uuid(), 'Adobe Audition', 'Vídeo & Animação', NOW()),
(gen_random_uuid(), 'Pro Tools',      'Vídeo & Animação', NOW()),
(gen_random_uuid(), 'Storyboard',     'Vídeo & Animação', NOW()),
(gen_random_uuid(), 'VFX',            'Vídeo & Animação', NOW()),
(gen_random_uuid(), 'Rotoscopia',     'Vídeo & Animação', NOW()),
(gen_random_uuid(), 'Compositing',    'Vídeo & Animação', NOW()),
(gen_random_uuid(), 'Subtitling',     'Vídeo & Animação', NOW()),
(gen_random_uuid(), 'Foley',          'Vídeo & Animação', NOW())
ON CONFLICT ("Name") DO NOTHING;

-- ── Skills: grupos novos ───────────────────────────────────────────────────
INSERT INTO "Skills" ("Id", "Name", "Group", "CreatedAt") VALUES
-- Idiomas (10)
(gen_random_uuid(), 'Inglês',                    'Idiomas', NOW()),
(gen_random_uuid(), 'Espanhol',                  'Idiomas', NOW()),
(gen_random_uuid(), 'Francês',                   'Idiomas', NOW()),
(gen_random_uuid(), 'Alemão',                    'Idiomas', NOW()),
(gen_random_uuid(), 'Italiano',                  'Idiomas', NOW()),
(gen_random_uuid(), 'Mandarim',                  'Idiomas', NOW()),
(gen_random_uuid(), 'Japonês',                   'Idiomas', NOW()),
(gen_random_uuid(), 'Tradução Juramentada',      'Idiomas', NOW()),
(gen_random_uuid(), 'Localização (l10n)',        'Idiomas', NOW()),
(gen_random_uuid(), 'Internacionalização (i18n)','Idiomas', NOW()),
-- Áudio & Música (12)
(gen_random_uuid(), 'Gravação de Áudio',  'Áudio & Música', NOW()),
(gen_random_uuid(), 'Mixagem',            'Áudio & Música', NOW()),
(gen_random_uuid(), 'Masterização',       'Áudio & Música', NOW()),
(gen_random_uuid(), 'Composição',         'Áudio & Música', NOW()),
(gen_random_uuid(), 'Produção Musical',   'Áudio & Música', NOW()),
(gen_random_uuid(), 'Sound Design',       'Áudio & Música', NOW()),
(gen_random_uuid(), 'Jingles',            'Áudio & Música', NOW()),
(gen_random_uuid(), 'Voice Over',         'Áudio & Música', NOW()),
(gen_random_uuid(), 'Edição de Áudio',    'Áudio & Música', NOW()),
(gen_random_uuid(), 'Logic Pro',          'Áudio & Música', NOW()),
(gen_random_uuid(), 'Ableton Live',       'Áudio & Música', NOW()),
(gen_random_uuid(), 'FL Studio',          'Áudio & Música', NOW()),
-- Fotografia (8)
(gen_random_uuid(), 'Fotografia de Produto',     'Fotografia', NOW()),
(gen_random_uuid(), 'Fotografia Corporativa',    'Fotografia', NOW()),
(gen_random_uuid(), 'Fotografia de Eventos',     'Fotografia', NOW()),
(gen_random_uuid(), 'Fotografia de Casamento',   'Fotografia', NOW()),
(gen_random_uuid(), 'Edição Lightroom',          'Fotografia', NOW()),
(gen_random_uuid(), 'Retoque Beauty',            'Fotografia', NOW()),
(gen_random_uuid(), 'Banco de Imagens',          'Fotografia', NOW()),
(gen_random_uuid(), 'Fotografia Aérea (Drone)',  'Fotografia', NOW()),
-- Negócios & Vendas (9)
(gen_random_uuid(), 'Plano de Negócios',          'Negócios & Vendas', NOW()),
(gen_random_uuid(), 'Modelagem Financeira',       'Negócios & Vendas', NOW()),
(gen_random_uuid(), 'Pitch Deck',                 'Negócios & Vendas', NOW()),
(gen_random_uuid(), 'Valuation',                  'Negócios & Vendas', NOW()),
(gen_random_uuid(), 'Captação de Investimento',   'Negócios & Vendas', NOW()),
(gen_random_uuid(), 'Vendas B2B',                 'Negócios & Vendas', NOW()),
(gen_random_uuid(), 'Vendas Consultivas',         'Negócios & Vendas', NOW()),
(gen_random_uuid(), 'Cold Calling',               'Negócios & Vendas', NOW()),
(gen_random_uuid(), 'LinkedIn Outreach',          'Negócios & Vendas', NOW()),
-- Jurídico (8)
(gen_random_uuid(), 'Contratos',                'Jurídico', NOW()),
(gen_random_uuid(), 'Termos de Uso',            'Jurídico', NOW()),
(gen_random_uuid(), 'Política de Privacidade',  'Jurídico', NOW()),
(gen_random_uuid(), 'LGPD Compliance',          'Jurídico', NOW()),
(gen_random_uuid(), 'Direito Tributário',       'Jurídico', NOW()),
(gen_random_uuid(), 'Direito Empresarial',      'Jurídico', NOW()),
(gen_random_uuid(), 'Direito Digital',          'Jurídico', NOW()),
(gen_random_uuid(), 'Marcas e Patentes',        'Jurídico', NOW()),
-- Educação & Tutoria (8)
(gen_random_uuid(), 'Aulas Particulares',         'Educação & Tutoria', NOW()),
(gen_random_uuid(), 'Criação de Cursos Online',   'Educação & Tutoria', NOW()),
(gen_random_uuid(), 'Material Didático',          'Educação & Tutoria', NOW()),
(gen_random_uuid(), 'Tutoria em Programação',     'Educação & Tutoria', NOW()),
(gen_random_uuid(), 'Tutoria em Matemática',      'Educação & Tutoria', NOW()),
(gen_random_uuid(), 'Apresentações Educacionais', 'Educação & Tutoria', NOW()),
(gen_random_uuid(), 'Gravação de Aulas',          'Educação & Tutoria', NOW()),
(gen_random_uuid(), 'Mentoria',                   'Educação & Tutoria', NOW()),
-- Arquitetura & Engenharia (11)
(gen_random_uuid(), 'AutoCAD',              'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'SketchUp',             'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'Revit',                'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'Lumion',               'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'ArchiCAD',             'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'Cálculo Estrutural',   'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'Projeto Hidráulico',   'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'Projeto Elétrico',     'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'Render 3D',            'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'Maquete Eletrônica',   'Arquitetura & Engenharia', NOW()),
(gen_random_uuid(), 'BIM',                  'Arquitetura & Engenharia', NOW()),
-- Games & XR (10)
(gen_random_uuid(), 'Unity',                       'Games & XR', NOW()),
(gen_random_uuid(), 'Unreal Engine',               'Games & XR', NOW()),
(gen_random_uuid(), 'Godot',                       'Games & XR', NOW()),
(gen_random_uuid(), 'Game Design',                 'Games & XR', NOW()),
(gen_random_uuid(), 'Level Design',                'Games & XR', NOW()),
(gen_random_uuid(), 'Modelagem 3D para Games',     'Games & XR', NOW()),
(gen_random_uuid(), 'Animação para Games',         'Games & XR', NOW()),
(gen_random_uuid(), 'Realidade Virtual',           'Games & XR', NOW()),
(gen_random_uuid(), 'Realidade Aumentada',         'Games & XR', NOW()),
(gen_random_uuid(), 'Blockchain Games',            'Games & XR', NOW())
ON CONFLICT ("Name") DO NOTHING;

COMMIT;

-- Resultado final
SELECT 'Categories total' AS metrica, COUNT(*) AS valor FROM "Categories"
UNION ALL SELECT 'Skills total', COUNT(*) FROM "Skills"
UNION ALL SELECT 'Skill groups', COUNT(DISTINCT "Group") FROM "Skills";
